"""Imoprt the cryp2bot function from the cryp2bot module and test it."""
from cryp2bot.cryp2bot import kraken


# Generated by Copilot

def test_kraken_server_time():
    """Test the kraken function with the 'server_time' command."""
    kraken('server_time')
