"""This is the cryp2bot module."""

import click
import cryp2bot.kraken.marketdata as marketdata


@click.group()
def cli():
    """add a group of commands to the command line interface."""


@cli.command()
@click.argument('currency', required=True)
def value(currency):
    """Get the ticker information for a given currency."""
    
    currency = currency.upper()

    if currency is None or currency.strip() == "":
        click.echo(click.style("The  argument is required.", fg="red"))
        return

    data = marketdata.value(currency)

    if data is None:
        click.echo(click.style("Failed to retrieve ticker information.", fg="red"))
        return

    database = {}

    for key in data:
        pair1 = key[:3]
        pair2 = key[4:]
        formatted_price = f"{data[key]:.2f}"
    
        if pair1 not in database:
            database[pair1] = {}
        
        database[pair1][pair2] = formatted_price

        if pair1 == "BTC":
            database[pair1]["BTC"] = 1    

    
    print(database)

    click.echo(click.style("\t\tEUR\t\tUSD\t\tBTC ", fg="green"))  # Generated by Copilot

    for key in database:
            click.echo(click.style(f"{key}\t\t{database[key]["EUR"]}\t\t{database[key]["USD"]}\t\t{database[key]["BTC"]}", fg="white"))





    for c in data:
        formatted_price = f"{data[c]:.2f}"
        click.echo(click.style(f"{c}:", fg="white") + click.style(f"\t{formatted_price.rjust(10)}", fg="blue"))

if __name__ == "__main__":
    cli()  # Call the main function to start the command line interface.
