import cryptoengine.kraken.marketdata as marketdata

# Generated by Copilot

def test_get_asset_data():
    """Test the `get_asset_data` function from the `marketdata` module."""

    assert str(marketdata.get_asset_data("BTCEUR")).find("XBT") > 0
    assert str(marketdata.get_asset_data("BTCUSD")).find("XBT") > 0
    assert str(marketdata.get_asset_data("BTC")).find("XBT") > 0

    assert str(marketdata.get_asset_data("SOLEUR")).find("SOL") > 0
    assert str(marketdata.get_asset_data("SOLUSD")).find("SOL") > 0
    assert str(marketdata.get_asset_data("SOL")).find("SOL") > 0

    assert str(marketdata.get_asset_data("ETHEUR")).find("ETH") > 0
    assert str(marketdata.get_asset_data("ETHUSD")).find("ETH") > 0
    assert str(marketdata.get_asset_data("ETH")).find("ETH") > 0

    assert str(marketdata.get_asset_data("EUR")).find("EUR") > 0

    assert not marketdata.get_asset_data("XXXXXX")

def test_get_value():
    """Test the `get_value` function from the `marketdata` module."""

    assert marketdata.get_value("BTCEUR") > 0
    assert marketdata.get_value("BTCUSD") > 0
    assert marketdata.get_value("BTC") > 0

    assert marketdata.get_value("SOLEUR") > 0
    assert marketdata.get_value("SOLUSD") > 0
    assert marketdata.get_value("SOL") > 0

    assert marketdata.get_value("ETHEUR") > 0
    assert marketdata.get_value("ETHUSD") > 0
    assert marketdata.get_value("ETH") > 0

    assert marketdata.get_value("EUR") > 0

    assert not marketdata.get_value("XXXXXX")
